---
title: "ForestHerNC_MPAnalysis"
author: "Emma Childs"
date: "2024-01-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r loading packages, include=FALSE, warning=FALSE, message=FALSE}

rm(list=ls())
library(ggplot2)
library(tidyr)
library(tidyverse)
library(plm)
library(GGally)
library(car)
library(lmtest)
library(sandwich)
library(gt)
library(ggrepel)
library(tinytex)
#installing and loading necessary packages
#tinytex::install_tinytex() when first starting to be able to knit into spiffy looking PDFs if necessary. 

```


```{r working directory, include=FALSE, warning=FALSE, message=FALSE}

#setwd("C:/Users/EmmaC/Documents/Duke_Academics/Fall_2023_Classes/MASTERS_PROJECT/R_Coding/FHNC_Rcode")
#don't need this code chunk bc I set up a R Project folder that renders this unnecessary. 

```


```{r reading in original FHNC survey data, include=FALSE, warning=FALSE, message=FALSE}

FHNC23.df<-read_csv("ORIGINAL_ForestHerNC_2023Implementation_Survey.csv") %>%
  glimpse()

FHNC23.df
#reading in CSV files for 2023 ForestHer NC end of year implementation survey. 

``` 


```{r correcting Qualtrics formatting}

FHNC23.data.df <- read_csv("ORIGINAL_ForestHerNC_2023Implementation_Survey.csv", 
    col_names = FALSE, skip = 3)
#reading in only data

FHNC23.Qs.df <- read_csv("ORIGINAL_ForestHerNC_2023Implementation_Survey.csv", 
    n_max = 1)
#reading in Qualtrics questions that get embedded in CSV file that we may want to use later.

my_colnames_vec <- colnames(FHNC23.Qs.df)

colnames(FHNC23.data.df) <- my_colnames_vec

```


```{r initial column cleaning}

FHNC23.clean.df <- FHNC23.data.df %>% 
  select(Progress, ResponseId, Q2:Q23)
#Eliminated several superfluous columns with information that was not needed for analysis (start time, end time, etc.)

```

COME BACK AND WORK HERE - 3.14.24

```{r cleaning for higher completion survey rates, eval=FALSE}

FHNC23.clean.df <- FHNC23.clean.df %>%
  filter(Progress > 20)
#Could come back and make this threshold higher depending on what I'm looking for. Do I want to select or filter for the threshold? Should I have a more intensive filter for the subset of coop mgmt data?

```


```{r group by mgmt activity}

#Direct vs indirect management - theme 2

#See Dakota's pivot table for further designations 

```


```{r group by topical theme}

#theme 1:
#education
#business management
#wildlife
#invasive species
#recreation
#timber/trees
#fire
```



```{r FHNC analyses}

#consult list of planned analyses

```


```{r subset cooperative data}

FHNC23.coop.df <- FHNC23.clean.df %>% 
  select(Progress, ResponseId, Q5, Q8_1:Q12, Q16:Q19) %>%
  filter(Progress > 80) 
#Selecting columns of interest, cooperative mgmt specific

```


```{r visualizing cooperative data Q8}

question_8_text <- FHNC23.Qs.df %>% 
  select(IPAddress, starts_with("Q8_")) %>% 
  pivot_longer(-IPAddress, names_to = "question", values_to = "question_text") %>% 
  mutate(question_short = str_remove(question_text, "Please select your level of interest in each of the following different services that cooperative forest management can offer. - Coordinating with adjacent landowners (on|to) ")) %>% 
  pull(question_short)
question_8_text
  
my_levels_8 <- c("Not Interested", "Not Sure", "Somewhat Interested", "Very Interested")
# my_levels_8 <- rev(c("Not Interested", "Not Sure", "Somewhat Interested", "Very Interested"))

# glimpse()
question_8_df <- FHNC23.coop.df %>% 
  select(ResponseId, starts_with("Q8_")) %>% 
  pivot_longer(-ResponseId, names_to = "question", values_to = "response") %>% 
  count(question, response) # %>% 
  # mutate(response = factor(response, levels = my_levels_8)) 

question_8_df
  # filter(Progress == 100) %>%
  # mutate(question = if_else(question == "Q8_1", "special", question))
  # mutate(question = case_when(
  #   question == "Q8_1" ~ "special-thing1",
  #   question == "Q8_2" ~ "special-thing2",
  #   TRUE ~ "foo"
  # ))
  # drop_na(response)
  # arrange(response, desc(n))

question_8_df %>% 
  ggplot(aes(x = question, y = n)) +
  geom_col(aes(fill = response)) 

# question_8_df %>% 
#   ggplot(aes(x = question, y = n)) +
#   geom_col(aes(fill = response)) +
#   facet_wrap(vars(question))

#Visualizing question 8 - coordinating services with other landowners - still need to make the visualization more nuanced. 
```


```{r visualizing cooperative data Q9}

question_9_text <- FHNC23.Qs.df %>% 
  select(IPAddress, starts_with("Q9_")) %>% 
  pivot_longer(-IPAddress, names_to = "question", values_to = "question_text") %>% 
  mutate(question_short = str_remove(question_text, "Please select the level of importance or unimportance for each of the following different benefits that cooperative forest management can offer. - ")) %>% 
  pull(question_short)
question_9_text
  
my_levels_9 <- c("Not Important", "Not Sure", "Somewhat Important", "Very Important")
# my_levels_9 <- rev(c("Not Important", "Not Sure", "Somewhat Important", "Very Inmportant"))

# glimpse()
question_9_df <- FHNC23.coop.df %>% 
  select(ResponseId, starts_with("Q9_")) %>% 
  pivot_longer(-ResponseId, names_to = "question", values_to = "response") %>% 
  count(question, response) # %>% 
  # mutate(response = factor(response, levels = my_levels_9)) 

question_9_df
  # filter(Progress == 100) %>%
  # mutate(question = if_else(question == "Q9_1", "special", question))
  # mutate(question = case_when(
  #   question == "Q9_1" ~ "special-thing1",
  #   question == "Q9_2" ~ "special-thing2",
  #   TRUE ~ "foo"
  # ))
  # drop_na(response)
  # arrange(response, desc(n))

question_9_df %>% 
  ggplot(aes(x = question, y = n)) +
  geom_col(aes(fill = response)) 

#Visualizing question 9 - potential different benefits that coordinated services could offer. Need to figure out what to do with the text/other option that is throwing my visualization out of order/making it confusing. 

```


```{r visualizing cooperative data Q10}

question_10_text <- FHNC23.Qs.df %>% 
  select(IPAddress, starts_with("Q10_")) %>% 
  pivot_longer(-IPAddress, names_to = "question", values_to = "question_text") %>% 
  mutate(question_short = str_remove(question_text, "Please select the level of significance or insignificance for each of the following different barriers to engaging in cooperative forest management for you and your land. - ")) %>% 
  pull(question_short)
question_10_text
  
my_levels_10 <- c("Not Significant", "Not Sure", "Somewhat Significant", "Very Significant")
# my_levels_10 <- rev(c("Not Significant", "Not Sure", "Somewhat Significant", "Very Significant"))

# glimpse()
question_10_df <- FHNC23.coop.df %>% 
  select(ResponseId, starts_with("Q10_")) %>% 
  pivot_longer(-ResponseId, names_to = "question", values_to = "response") %>% 
  count(question, response) # %>% 
  # mutate(response = factor(response, levels = my_levels_9)) 

question_10_df
  # filter(Progress == 100) %>%
  # mutate(question = if_else(question == "Q10_1", "special", question))
  # mutate(question = case_when(
  #   question == "Q10_1" ~ "special-thing1",
  #   question == "Q10_2" ~ "special-thing2",
  #   TRUE ~ "foo"
  # ))
  # drop_na(response)
  # arrange(response, desc(n))

question_10_df %>% 
  ggplot(aes(x = question, y = n)) +
  geom_col(aes(fill = response))

#Visualizing question 10 - the level of significance or insignificance for each of the following different barriers to engaging in cooperative forest management for you and your land.


```


```{r visualizing cooperative data Q11}

question_11_text <- FHNC23.Qs.df %>% 
  select(IPAddress, starts_with("Q11_")) %>% 
  pivot_longer(-IPAddress, names_to = "question", values_to = "question_text") %>% 
  mutate(question_short = str_remove(question_text, "To what degree would each of the following allow you to engage in cooperative forest management? - ")) %>% 
  pull(question_short)
question_11_text
  
my_levels_11 <- c("Not at all", "Not Sure", "Somewhat", "Greatly")
# my_levels_11 <- rev(c("Not at all", "Not Sure", "Somewhat", "Greatly"))

# glimpse()
question_11_df <- FHNC23.coop.df %>% 
  select(ResponseId, starts_with("Q11_")) %>% 
  pivot_longer(-ResponseId, names_to = "question", values_to = "response") %>% 
  count(question, response) # %>% 
  # mutate(response = factor(response, levels = my_levels_11)) 

question_11_df
  # filter(Progress == 100) %>%
  # mutate(question = if_else(question == "Q11_1", "special", question))
  # mutate(question = case_when(
  #   question == "Q11_1" ~ "special-thing1",
  #   question == "Q11_2" ~ "special-thing2",
  #   TRUE ~ "foo"
  # ))
  # drop_na(response)
  # arrange(response, desc(n))

question_11_df %>% 
  ggplot(aes(x = question, y = n)) +
  geom_col(aes(fill = response)) 

# question_11_df %>% 
#   ggplot(aes(x = question, y = n)) +
#   geom_col(aes(fill = response)) +
#   facet_wrap(vars(question))

#Visualizing question 11 - To what degree would each of the following allow you to engage in cooperative forest management?

#Something is WRONG here - I want to get rid of 11_7_TEXT bc it is messing up the visualization...how??? Tried adding "ends_with("Q11_7")" on line after "starts_with" but that didn't work. 

```


```{r recode cooperative Qs to numeric}

#Qs 8-11 (12 also is a coop Q but character response) - need to match USFS coding - add column for 1-5 values?
```


```{r test run analyses}

#barchart/histogram by response type (1-5)?...and then could do a further visualization by region? Or could run more statistical analyses. 

```

# Go through each question and figure out what value I want or need from that Q for analysis. (Prioritize the columns I know that I want, and then work backyards.)

#Start recoding Likert cooperative Qs to be numeric - can use recode() or other code Lauren sent - use same numeric values that USFS uses that Jesse sent
